image: node:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$EWAL_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chown $USER ~/.ssh/config
  - chmod 644 ~/.ssh/config
  - ssh -vvv "root@${HOST}"
  - alias cnpm="npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc"

cache:
  paths:
  - node_modules/
  - dist

build:
  stage:
    build
  script:
    - cnpm install
    - cnpm run build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
      - dist

  

deploy:
  stage:
    deploy
  script:
    - tar czf dist.tar.gz dist
    - scp dist.tar.gz "root@${HOST}:/data/wwwroot"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules
      - dist
